GET http://localhost:3000/movies.json
###
POST http://localhost:3000/movies.json
Content-Type: application/json

{
  "title": "Star Wars: Attack of the Clones", 
  "year": 2002, 
  "plot": "The long awaited war between the light side of the force and the dark side of the force begins."
}
###
GET http://localhost:3000/movies/6.json
###
PATCH http://localhost:3000/movies/11.json
Content-Type: application/json

{"director": "Joe Frank"}

###
DELETE  http://localhost:3000/movies/7.json
Content-Type: application/json
###
GET http://localhost:3000/actors.json
###
POST http://localhost:3000/actors.json
Content-Type: application/json

{
  "first_name": "Leonardo",  
  "last_name": "DiCaprio",    
  "known_for": "Titanic",
  "age": 78,
  "gender": "m"
}

###
GET http://localhost:3000/actors/36.json
###
PATCH http://localhost:3000/actors/38.json
Content-Type: application/json

{ 
  "first_name": "Will",  
  "last_name": "Smith",    
  "known_for": "Aladin", 
  "age": 45,
  "gender": "m"
}

###
DELETE  http://localhost:3000/actors/35.json
Content-Type: application/json